import { Itinerary } from '../types';

export const MOCK_ITINERARY: Itinerary = {
  id: 'mock-001',
  destination: 'Barcelona, Spain',
  destinationImageQuery: 'barcelona spain',
  heroEmoji: '🏖️',
  tripInput: {
    destination: 'Barcelona, Spain',
    startDate: new Date('2025-07-10'),
    endDate: new Date('2025-07-13'),
    adults: 2,
    kids: 2,
    kidAges: [5, 8],
    accessibility: ['stroller'],
    vibes: ['Foodie', 'Kid-Friendly', 'History', 'Beach'],
    includeDining: true,
    pace: 'balanced',
    budget: 'mid-range',
    stayLocation: 'Eixample district',
    dietaryNeeds: [],
    cuisinePrefs: ['Local', 'Mediterranean'],
  },
  days: [
    {
      day: 1,
      date: 'Thursday, July 10',
      theme: 'Arrival & Gothic Quarter',
      activities: [
        {
          time: '10:00 AM',
          title: 'Check-in & Settle',
          description: 'Arrive at your hotel in the Eixample district -- stroller-friendly neighborhood with wide pavements and easy Metro access.',
          duration: '1 hour',
          category: 'transit',
          cost: 'Hotel',
        },
        {
          time: '11:30 AM',
          title: 'Gothic Quarter Walking Tour',
          description: 'Wander the ancient labyrinth of the Gothic Quarter. Stick to the main pedestrian streets -- most are stroller-accessible.',
          duration: '2 hours',
          category: 'activity',
          accessibilityNotes: 'Some narrow cobblestone alleys -- keep to Carrer del Bisbe and Las Ramblas for stroller ease.',
          tips: 'Kids love the "hidden" Roman wall ruins on Plaça Nova -- feel free to let them touch!',
          cost: 'Free',
        },
        {
          time: '1:30 PM',
          title: 'Lunch at La Boqueria Market',
          description: 'Grab fresh tapas, empanadas, and fruit at stalls in the iconic covered market -- 5 mins from the Gothic Quarter.',
          duration: '1 hour',
          category: 'activity',
          tips: 'Order at stalls, not sit-down restaurants inside -- faster, cheaper, and kids can point at what they want.',
          cost: '~$12/person',
        },
        {
          time: '3:00 PM',
          title: 'Barcelona Beach (Barceloneta)',
          description: 'A short Metro ride to the beach. The sand is wide and flat -- perfect for strollers. Lifeguards on duty in July.',
          duration: '2.5 hours',
          category: 'activity',
          accessibilityNotes: 'Accessible beach mats available at the north end of Barceloneta.',
          tips: 'Arrive before 4 PM to get a good spot -- it fills up fast in summer.',
          cost: 'Free',
        },
      ],
      diningSpots: [
        { meal: 'breakfast', nearActivity: 'Gothic Quarter Walking Tour', options: [
          { name: 'Bar Marsella', cuisine: 'Classic Barcelona café', why: 'One of the oldest bars in Barcelona — locals stop here for café amb llet before work. Unchanged interior since 1820.', cost: '~$5/person', dietaryTags: ['Vegetarian'] },
          { name: 'Federal Café', cuisine: 'Australian-style brunch', why: 'Packed with Eixample locals on weekends. Excellent avocado toast and specialty coffee. High chairs available.', cost: '~$10/person', dietaryTags: ['Vegetarian'] },
        ]},
        { meal: 'lunch', nearActivity: 'Gothic Quarter Walking Tour', options: [
          { name: 'La Boqueria stalls', cuisine: 'Catalan market food', why: 'Skip the restaurants inside — go straight to the stalls. Jamón, fresh fruit, empanadas eaten standing. Locals have done this for generations.', cost: '~$10/person', dietaryTags: [] },
          { name: 'Bar Cañete', cuisine: 'Traditional Catalan tapas', why: 'A Barcelona institution beloved by locals for its market-driven menu. Standing bar or sit-down — both great.', cost: '~$18/person', dietaryTags: [] },
        ]},
        { meal: 'dinner', nearActivity: 'Barcelona Beach (Barceloneta)', options: [
          { name: 'El Xampanyet', cuisine: 'Catalan tavern', why: 'Neighbourhood institution in El Born since 1929. House-made cava and patatas bravas — this is the real deal, not a tourist version.', cost: '~$22/person', dietaryTags: ['Vegetarian'] },
          { name: 'La Mar Salada', cuisine: 'Modern Catalan seafood', why: 'Just off the beach, loved by locals for fresh paella and fideuà. Better value and quality than the beachfront tourist traps.', cost: '~$28/person', dietaryTags: [] },
        ]},
      ],
    },
    {
      day: 2,
      date: 'Friday, July 11',
      theme: 'Gaudi & Parc Güell',
      activities: [
        {
          time: '9:00 AM',
          title: 'Breakfast at Federal Café',
          description: 'Cozy café with avocado toast, pancakes, and excellent coffee. High chairs available. 8 mins walk from hotel.',
          duration: '45 mins',
          category: 'activity',
          cost: '~$10/person',
        },
        {
          time: '10:00 AM',
          title: 'Sagrada Familia',
          description: "Gaudi's masterpiece -- the towers and stained glass are genuinely jaw-dropping for kids and adults alike.",
          duration: '2 hours',
          category: 'activity',
          accessibilityNotes: 'Fully wheelchair and stroller accessible. Elevators in the towers.',
          tips: 'Book skip-the-line tickets online the night before. Aim for the 10 AM slot for best light through the windows.',
          cost: '~$32/adult, ~$18/child',
        },
        {
          time: '12:30 PM',
          title: 'Lunch at Cerveceria Catalana',
          description: 'Best pintxos in Eixample -- 6 mins from Sagrada Familia. Kids will love pointing at the bar display.',
          duration: '1 hour',
          category: 'activity',
          cost: '~$18/person',
        },
        {
          time: '2:00 PM',
          title: 'Parc Güell',
          description: "Gaudi's surreal mosaic park with city views. The Monumental Zone requires tickets -- the rest is free.",
          duration: '2 hours',
          category: 'activity',
          accessibilityNotes: 'Stroller-friendly paths in the free zone. Monumental Zone has some steps -- use the ramps on the east side.',
          tips: 'The dragon staircase is the best photo spot -- go first thing before crowds gather.',
          cost: '~$14/adult, free under 7',
        },
        {
          time: '5:00 PM',
          title: 'Rest Hour at Hotel',
          description: 'Build in a rest window -- 8-year-olds can handle a full day, 5-year-olds will hit a wall by late afternoon.',
          duration: '1 hour',
          category: 'rest',
        },
      ],
      diningSpots: [
        { meal: 'breakfast', nearActivity: 'Sagrada Familia', options: [
          { name: 'Federal Café', cuisine: 'Australian-style brunch', why: 'Go-to for Eixample locals — proper specialty coffee and avocado toast. High chairs available.', cost: '~$10/person', dietaryTags: ['Vegetarian'] },
          { name: 'Alsur Café', cuisine: 'Modern café brunch', why: 'Industrial-chic neighbourhood café near the Rambla del Poblenou. Locals swear by the granola bowls.', cost: '~$9/person', dietaryTags: ['Vegetarian', 'Gluten-free'] },
        ]},
        { meal: 'lunch', nearActivity: 'Sagrada Familia', options: [
          { name: 'Cerveceria Catalana', cuisine: 'Pintxos & tapas', why: 'Packed with locals for a reason — extraordinary pintxos bar display. 6 min from Sagrada Família but worlds away from the tourist crowds.', cost: '~$16/person', dietaryTags: ['Vegetarian'] },
          { name: 'Parking Pizza', cuisine: 'Neapolitan pizza', why: 'Barcelona cult favourite. Long queues of locals at lunch — they come for the wood-fired crusts and natural wines.', cost: '~$14/person', dietaryTags: ['Vegetarian'] },
        ]},
        { meal: 'dinner', nearActivity: 'Parc Güell', options: [
          { name: 'Bar Calders', cuisine: 'Neighbourhood tapas', why: 'Sant Antoni favourite with a large terrace. Locals come for the vermouth and patatas bravas. Great for kids who need room to move.', cost: '~$18/person', dietaryTags: ['Vegetarian'] },
          { name: 'Bodega Sepúlveda', cuisine: 'Classic Catalan wine bar', why: 'Old-school neighbourhood bodega beloved by locals. Simple menu, extraordinary wine selection, zero tourist clientele.', cost: '~$20/person', dietaryTags: [] },
        ]},
      ],
    },
    {
      day: 3,
      date: 'Saturday, July 12',
      theme: 'CosmoCaixa & Tibidabo',
      activities: [
        {
          time: '9:30 AM',
          title: 'CosmoCaixa Science Museum',
          description: 'The best family museum in Barcelona -- a genuine Amazon rainforest inside, dinosaur fossils, and a planetarium.',
          duration: '3 hours',
          category: 'activity',
          accessibilityNotes: 'Fully accessible. Wide ramps throughout.',
          tips: 'The Flooded Forest section has live animals -- kids aged 5-8 absolutely lose their minds here.',
          cost: '~$6/adult, free under 16',
        },
        {
          time: '3:00 PM',
          title: 'Tibidabo Amusement Park',
          description: '100-year-old hilltop amusement park with rides for all ages. The city views from the top are incredible.',
          duration: '3 hours',
          category: 'activity',
          accessibilityNotes: 'Stroller-friendly. Most rides accommodate 5+ year-olds.',
          tips: 'The Funicular up the hill is half the fun. Avoid weekends in August -- too crowded.',
          cost: '~$35/person',
        },
      ],
      diningSpots: [
        { meal: 'coffee', nearActivity: 'CosmoCaixa Science Museum', options: [
          { name: 'Bar Tomàs', cuisine: 'Old-school Barcelona bar', why: 'Famous in Sarrià for the best patatas bravas in the city — a debate locals have been having since 1968.', cost: '~$6/person', dietaryTags: ['Vegetarian'] },
          { name: 'Syra Coffee', cuisine: 'Specialty coffee', why: 'Barcelona\'s most respected specialty roaster. Locals bring laptops and spend mornings here. Kid-friendly tables outside.', cost: '~$5/person', dietaryTags: ['Vegetarian', 'Vegan'] },
        ]},
        { meal: 'lunch', nearActivity: 'CosmoCaixa Science Museum', options: [
          { name: 'Museu de la Ciència Cafeteria', cuisine: 'Simple café', why: 'On-site terrace with good views — unbeatable convenience on a museum day with kids. Go early to beat the queue.', cost: '~$12/person', dietaryTags: ['Vegetarian'] },
          { name: 'Can Travi Nou', cuisine: 'Traditional Catalan farmhouse', why: 'A 17th-century farmhouse in a park setting, beloved by Barcelona families for Sunday lunch. Real local food, zero tourist vibe.', cost: '~$20/person', dietaryTags: [] },
        ]},
        { meal: 'dinner', nearActivity: 'Tibidabo Amusement Park', options: [
          { name: 'Restaurante 7 Portes', cuisine: 'Classic Catalan', why: 'A Barcelona institution since 1836. Every local has eaten here for a special occasion. Famous for paella and fideuà.', cost: '~$30/person', dietaryTags: [] },
          { name: 'La Pepita', cuisine: 'Creative Catalan small plates', why: 'Neighbourhood favourite in Gràcia — creative tasting plates and natural wines. Locals book weeks ahead.', cost: '~$22/person', dietaryTags: ['Vegetarian'] },
        ]},
      ],
    },
  ],
  highlights: [
    'Stroller-accessible routes throughout',
    'Kid rest windows built into each afternoon',
    'All dining within 10 minutes of each activity',
    'Mix of world-class sights and genuine local spots',
  ],
  packingTips: [
    'Stroller with sun canopy -- Barcelona gets very hot in July',
    'Portable fan or spray bottle for the kids',
    'Reusable water bottles -- tap water is safe and free',
    'EU travel adapter if coming from US/UK',
    "Kids' swimwear for Barceloneta beach",
  ],
  generatedAt: new Date(),
};
